/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP 1000 [LOSS_REASON_SID]
      ,[LV4_CODE]
      ,[LV4_DESC]
      ,[LV4_DESC_SHORT]
      ,[LV3_CODE]
      ,[LV3_DESC]
      ,[LV2_CODE]
      ,[LV2_DESC]
      ,[LV1_CODE]
      ,[LV1_DESC]
      ,[LV0_CODE]
      ,[LV0_DESC]
      ,[CONNECT_MAPPING]
      ,[OWNERSHIP_CODE]
      ,[OWNERSHIP_DESC]
      ,[IS_CCFOT]
      ,[OK_FLAG]
      ,[STATUS_NOTE]
      ,[LAST_UPD_DT]
      ,[JOB_ID]
  FROM [odw_dm].[odw_user].[D_LOSS_REASON]